
const TEXT_VERTICAL_MARGIN = 15;

const TEXT_HORIZONTAL_MARGIN = 9;

const ROW_CONTAINER_HEIGHT = 65;

const ROW_HEIGHT = ROW_CONTAINER_HEIGHT - 5;

const PRIMARY_COLOR = "rgb(191,38,0)";

const PRIMARY_COLOR_LIGHT = "rgb(237,223,220)";

const LEFT_FIRST_MARGIN = 15;

const RIGHT_FIRST_MARGIN = 15;

const ICON_CONTAINER_WIDTH = 37;

const LEFT_SECOND_MARGIN = LEFT_FIRST_MARGIN + ICON_CONTAINER_WIDTH + TEXT_HORIZONTAL_MARGIN;

const RIGHT_SECOND_MARGIN = 25 + RIGHT_FIRST_MARGIN;

const CONTAINER_VERTICAL_MARGIN = 15;

const CONTAINER_ELEVATION = 5;

const SECONDARY_COLOR = "rgb(7,99,5)";

const MODAL_ROW_HEIGHT = 50;

const OVERLAY = "rgba(15,15,15,0.6)";

const MODAL_VERTICAL_PADDING = 10;

const TEXT_GREY = "rgb(70,70,70)";

const TAB_GREY = TEXT_GREY;

const PLACEHOLDER_GREY = "rgb(150, 150, 150)";

const BACKGROUND_GREY = "rgb(230, 230, 230)";

const BORDER_GREY = "rgb(200, 200, 200)";

const Defaults = {
    TEXT_VERTICAL_MARGIN,
    TEXT_HORIZONTAL_MARGIN,
    ROW_CONTAINER_HEIGHT,
    ROW_HEIGHT,
    PRIMARY_COLOR,
    PRIMARY_COLOR_LIGHT,
    SECONDARY_COLOR,
    LEFT_FIRST_MARGIN,
    LEFT_SECOND_MARGIN,
    RIGHT_FIRST_MARGIN,
    RIGHT_SECOND_MARGIN,
    CONTAINER_VERTICAL_MARGIN,
    CONTAINER_ELEVATION,
    MODAL_ROW_HEIGHT,
    OVERLAY,
    MODAL_VERTICAL_PADDING,
    TEXT_GREY,
    TAB_GREY,
    PLACEHOLDER_GREY,
    BACKGROUND_GREY,
    BORDER_GREY,
    ICON_CONTAINER_WIDTH,
    
}

export default Defaults